### PR TITLE
Adding feature to handle HeroImage

### PR DESCRIPTION
**Pull request by UniverseCitiz3n**
As in #80 
I've added some lines in New-BurntToastNotification to give ability to users to show custom HeroImage

### CODE REVIEW

**Comment by Windos** [comment]
Thanks for this @UniverseCitiz3n, I'm a bit snowed under atm so it may take a little bit of time for me to process this. I have added the hacktoberfest tags though, just in case you're taking part in that this year 😄

**Comment by UniverseCitiz3n** [comment]
@Windos yeah sure, take your time, man 😄 
And thanks for HACKTOBERFEST label 🤟

**Comment by Windos** [comment]
Thanks again for this PR @UniverseCitiz3n

**Comment by UniverseCitiz3n** [comment]
Great 🙂
Merry Christmas 🎄

**Pull request merged**
